# Generated by Django 2.2.6 on 2019-10-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='designation_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_id',
        ),
    ]
